### ISSUE TITLE
Config Database

### ISSUE THREAD

**Issue by ghost** [ThatOneHomelessGuy/togsclantags#1]
I put the **"database.cfg"** config but it did not work.

```
"togsclantags"
	{
		"driver"			"mysql"
		"host"				"YOURHOSTHERE"
		"database"			"DB_NAME"
		"user"				"DB_USER"
		"pass"				"USER_PW"
		"timeout"			"300"
	}
```

It would have to be **"localhost"** instead of **"YOURHOSTHERE"**

**Comment by ThatOneHomelessGuy** [comment]
Those are each just placeholders to give you an idea of what it might look like. Host can be an IP, a web address, or, if the server is on the same machine as your MySQL, it can be "localhost". Similarly, you will need to fill in the database name, user, and password. This applies to all plugins that use MySQL databases via databases.cfg. If you have sourcebans or something similar, it would likely be the same host that that plugin is using.

**Comment by ghost** [comment]
So based on what you said it would look like this:
```
"togsclantags"
	{
		"driver"			"mysql"
		"host"				"localhost"
		"database"			"DB_NAME"
		"user"				"DB_USER"
		"pass"				"USER_PW"
		"timeout"			"300"
	}
```
The database, user and pass would have to create also correct, just ask for ohost from the server?

**Comment by ThatOneHomelessGuy** [comment]
In many cases, the website will not be on the same machine as the server if you are renting from a game-server provider (GSP) host. Please paste your sourcebans setup here (blank out the password), and I can give you more information about your situation and how to set it up and work with your GSP. Do you have a CPanel page for your website?

**Comment by paulocrash** [comment]
So my server is rented by a company, they even do the installation of HLStatsX: CE the SourceBans I have not hired, but I asked them, they said that only by hiring their hosting service for me to be able to create a connection in MySQL.

Would you like to know why this connection to MySQL is necessary?

**Comment by ghost** [comment]
**I was able to create a connection with MySQL so the database looked like this:**
```
"togsclantags"
	{
		"driver"			"mysql"
		"host"				"mysql.hostinger.com.br"
		"database"			"u441339713_hsgam"
		"user"				"u441339713_hsgam"
		"pass"				"XXXXXX"
		"timeout"			"300"
	}
```
**I configured cvars like this:**
```
togsclantags_admflag "z"
togsclantags_bots "1"
togsclantags_enforcetags "1"
togsclantags_updatefreq "0"			
togsclantags_use_mysql "1"		
```	
It just does not display the TAGS yet.

I went on the server console and typed the sm plugins list to display the plugin, gave the following error in the plugin:
` 58 <Failed> "TOG Clan Tags" (2.2.0) by That One Guy`

It does not display any errors outside this!!!

What could it be?

**Comment by ThatOneHomelessGuy** [comment]
With you sm plugins list cmd, at the very bottom, it will list why a plugin has failed. Also, I edited your response to remove your password from it. Also, feel free to add me on steam for support.
http://steamcommunity.com/id/togcoding/

**Comment by ghost** [comment]
I did the test with SQLite and it worked I will do a new test with MySQL again post here if there is an error.

**Comment by ThatOneHomelessGuy** [comment]
Ok. If you need help setting up the database, let me know.

**Comment by ThatOneHomelessGuy** [comment]
P.S. The plugin isnt made for SQLite. I even just added a SetFailState to make that clear. Since I havent heard from you in a bit, I'll close this help-request out. Feel free to PM me on AM or steam.

**Comment by 3GaNwO** [comment]
Hey That one homeless guy I'm having a similar issue! 

So I want to MySQL the plugin but the service provider I have makes me use a prefix for my databases and I dont see anywhere in your cfg to allow me to change the default database. 

My question is how do I script the plugin so it reads the correct database. 
Example: I think your plugin looks for "togsclantags" in the MySQL database but my Service provider didnt give me root access and I had to make mine say "teamwit_togsclantags"

Is there a way you could help me with this perhaps? :)

**Comment by ThatOneHomelessGuy** [comment]
3GaNwO, please create your own thread in the future.

Nowhere in the plugin does it assume the database name. It assumes the setup name in databases.cfg though. Copying from the OP,

	"togsclantags"
	{
		"driver"				"mysql"
		"host"				"YOURHOSTHERE"
		"database"			"DB_NAME"
		"user"				"DB_USER"
		"pass"				"USER_PW"
		"timeout"				"300"
	}

So, you paste the above in databases.cfg, then fill it out. Put "teamwit_togsclantags" where it says "DB_NAME". Then, set your host/username/pw for it, etc.
