### ISSUE TITLE
[REQUEST] Admin Groups

### ISSUE THREAD

**Issue by BlackYuzia** [ThatOneHomelessGuy/togsclantags#5]
Hello @ThatOneHomelessGuy 
I have one idea what do that plugin better.
Now, TAGS work only from flags, add pls **admin groups** too.
Example: 
"Small Admin Setup"
	{
		// "flag"		"" 
               "group"            "Small Admin" // most support all lang and
		"tag"		"[Small Admin]"
	}

**Comment by ThatOneHomelessGuy** [comment]
I have no intention of adding this feature, but you are welcome to create the code and submit a pull request if you wish.
