### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by 3GaNwO** [ThatOneHomelessGuy/togsclantags#7]
L 08/03/2018 - 18:54:59: --------------------------------------------------------------------------
L 08/03/2018 - 18:54:59: Type	Timer |	Count	29251
L 08/03/2018 - 18:54:59: Type	CellArray |	Count	4
L 08/03/2018 - 18:54:59: -- Approximately 9712 bytes of memory are in use by (29255) Handles.
L 08/03/2018 - 18:54:59: [SM] MEMORY LEAK DETECTED IN PLUGIN (file "togsclantags.smx")
L 08/03/2018 - 18:54:59: [SM] Unloading plugin to free 29255 handles.
L 08/03/2018 - 18:54:59: [SM] Contact the author(s) of this plugin to correct this error.
L 08/03/2018 - 18:54:59: --------------------------------------------------------------------------

I just started running a FFA DM server and now I have this in my errors which is weird since none of my retake servers show this memory leak. There is a new plugin in my setup that I have been testing out and I guess my WS skins arent working now too idk I think it may be something in my setup but I figured I'd contact you just to get clarification (:

**Comment by 3GaNwO** [comment]
Okay so I updated Sourcemod and I guess there are no more errors sorry for posting this issue

**Comment by ThatOneHomelessGuy** [comment]
No problem...Let me know if it returns. When sourcemod nears the limit of available handles, it closes whichever plugins have the most handles open, assuming it is the culprit. That said, it seems weird that so many handles are open, and unless sourcemod version is the culprit, there may actually be one. Let me know if it returns. I'll close this for now.
